Omit GCC build
Because Travis machines do not have enough memory, it seems.

https://circleci.com/gh/ethereum/testeth/128?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
```
[179/243] Building CXX object
test/CMakeFiles/testeth.dir/tools/jsontests/StateTests.cpp.o
FAILED: test/CMakeFiles/testeth.dir/tools/jsontests/StateTests.cpp.o
/usr/bin/g++-6   -DETH_FATDB -Iinclude -I/home/builder/project
-I/home/builder/project/utils -I/home/builder/project/evmjit/include
-I/home/builder/project/hera/src -isystem
/home/builder/.hunter/_Base/a412c45/484bebf/2450d4d/Install/include
-isystem deps/include -isystem
/home/builder/.hunter/_Base/a412c45/484bebf/2450d4d/Install/include/cryptopp
-isystem deps/src/binaryen/src -Og -g -DETH_DEBUG
-fstack-protector-strong -Wall -Wextra -Werror -Wno-unknown-pragmas -g
--coverage -std=c++11 -MD -MT
test/CMakeFiles/testeth.dir/tools/jsontests/StateTests.cpp.o -MF
test/CMakeFiles/testeth.dir/tools/jsontests/StateTests.cpp.o.d -o
test/CMakeFiles/testeth.dir/tools/jsontests/StateTests.cpp.o -c
/home/builder/project/test/tools/jsontests/StateTests.cpp
In file included from
/home/builder/.hunter/_Base/a412c45/484bebf/2450d4d/Install/include/boost/test/unit_test.hpp:19:0,
                 from
/home/builder/project/test/tools/jsontests/StateTests.cpp:24:
/home/builder/project/test/tools/jsontests/StateTests.cpp:220:1: fatal
error: error writing to /tmp/cc2DLTzl.s: Cannot allocate memory
 BOOST_AUTO_TEST_SUITE_END()
 ^
compilation terminated.
```